# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-us

zh:
  locale: zh-Hans
  title: 李响
  params:
    description: 李响的个人学术主页——研究方向包括神经组合优化、深度学习与强化学习。
