# Navigation Links
# English menu
main:
  - name: Bio
    url: /
    weight: 10
    language: en
  - name: Papers
    url: /#papers
    weight: 20
    language: en
  - name: Campus Experience
    url: /#campus
    weight: 30
    language: en
  - name: Projects
    url: /#projects
    weight: 40
    language: en
  - name: Awards
    url: /#awards
    weight: 40
    language: en

# Chinese menu
zh_main:
  - name: 简介
    url: /
    weight: 10
    language: zh
  - name: 论文
    url: /#papers
    weight: 20
    language: zh
  - name: 校园经历
    url: /#campus
    weight: 30
    language: zh
  - name: 项目
    url: /#projects
    weight: 40
    language: zh
  - name: 获奖
    url: /#awards
    weight: 40
    language: zh
